### ISSUE TITLE
Texture template

### ISSUE THREAD

**Issue by MaximusRZ** [luizrenault/a-29b-community#11]
Hi there! Any chance to get your template? I want to paint some skins, Thanks

**Comment by denissoliveira** [comment]
I have very good material and texture that I made for the SF2 simulator (which can be downloaded at combatace.com), I would really like to help with the texture but I am currently making a cockpit for the SF2 mirage F1 series.

https://drive.google.com/drive/folders/1pRdGNK8QK5yt1aJhe024BZBADT0XeGUS?usp=sharing

**Comment by luizrenault** [comment]
Hi. We are currently working on a new external 3d model that we are planning on releasing soon.
We will release this new model with a proper template.

**Comment by denissoliveira** [comment]
The link on my google drive has an improved texture, maybe it helps.

**Comment by luizrenault** [comment]
I'll include them as FAB2 livery on next release.
Are you the author of the textures?

**Comment by denissoliveira** [comment]
yes, Denis Oliveira

**Comment by MaximusRZ** [comment]
https://drive.google.com/file/d/1pfIuisQncKWeRNpdsP5nn4e2Y5Q-mEJZ/view?usp=sharing

**Comment by luizrenault** [comment]
The file does not exist. Please submit it again.

**Comment by chunney** [comment]
muy buenas amigo tendrías las plantillas para poder hacer las de nuestro pías ya que contamos con este avión y queremos armar una comunidad

**Comment by MaximusRZ** [comment]
> muy buenas amigo tendrías las plantillas para poder hacer las de nuestro pías ya que contamos con este avión y queremos armar una comunidad

Buenas!! estoy armando un Template, cuando tenga el detalle terminado lo voy a compartir, lo estamos armando con Alex que se ocupo de hacer la capa de suciedad, publique un par de Screenshots en Razbam pero los han borrado, parece que les molesta jajaja
![image](https://user-images.githubusercontent.com/80410123/111311207-b3584b80-863c-11eb-8728-0c732785d4c0.png)

**Comment by chunney** [comment]
QUE GENIA HERMANO si me lo podes pasar asi mismo como lo tenes es casi igual al de paraguay 

![image](https://user-images.githubusercontent.com/54551631/111374657-203f0600-867c-11eb-85af-59069972c38c.png)

**Comment by chunney** [comment]
![image](https://user-images.githubusercontent.com/54551631/111374951-77dd7180-867c-11eb-81a5-1c42a6396c00.png)

**Comment by luizrenault** [comment]
Please share the liveries so I can publish them on next release.
Please also state that we are authorized to share them.
@MaximusRZ

**Comment by MaximusRZ** [comment]
> Please share the liveries so I can publish them on next release.
> Please also state that we are authorized to share them.
> @MaximusRZ

Sure but those will be fictional since Argentina only has the regular Tucano not the Super.

**Comment by chunney** [comment]
@MaximusRZ hermano pasame xfa tus texturas
