### ISSUE TITLE
cant control the plane

### ISSUE THREAD

**Issue by swiftyr** [luizrenault/a-29b-community#112]
so i downloaded the aircraft installed it like every other mod but when i enter the free flight cold start or even a mission with it it doesnt let me control it i get replaced by a bot ):

**Comment by luciusMessias** [comment]
DO YOU REMENBER TO CONFIGURE THE CONTROLS?

**Comment by lampalork85** [comment]
Same problem here, i'm replaced by a bot, controls are configured

**Comment by retro-head** [comment]
Reporting same problem. Controls configured, when mission or instant action is started, the plane is shown from outside and you cant change to cockpit via F1, nor you cant take control via rALT+J.

Tested removing/deleting the mod and then "reinstalling" from fresh download as of today.
Tested in both flat screen and VR.
Other mods like T-45 work no problem.
DCS Steam Edition is V2.8.1.34667

any thoughts?

**Comment by luizrenault** [comment]
Are you using latest release?
Please attach log file.

**Comment by retro-head** [comment]
according to mods readme, Im using the Version 0.5.2 - 25 Jan 2023 downloaded yesterday from this repository.

Which log file you need? The dcs.log or the debrief.log, from DCS/Logs folder?

**Comment by retro-head** [comment]
[dcs.log](https://github.com/luizrenault/a-29b-community/files/10881047/dcs.log)

**Comment by luizrenault** [comment]
> Other mods like T-45 work no problem. DCS Steam Edition is V2.8.1.34667

This mod is only tested for latest beta which is 2.8.2.35759.
There is not enough requests for stable that justifies having both versions.

**Comment by retro-head** [comment]
And btw, thank you for your effort and excellent work on the mod, I love this aircraft.

**Comment by luizrenault** [comment]
When I use DCS API like FLIR for example the mod DLL needs to be fully compatible with the specific DCS version.
If i use nothing, like other mods, it is not needed to match.

**Comment by retro-head** [comment]
I dont need FLIR at the moment.

Strange that not many people complaining that the A-29b is not working with stable DCS version, is everybody using the beta?
