### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by HeadSplash** [luizrenault/a-29b-community#113]
I downloaded the latest release today to give it another shot. i ve tried this mod a few month ago and it was good so far but with this version DCS crashes everytime when i choose the client slot. i ve deleted the older files before i installed the new version.

**Comment by Cohen-Koen** [comment]
I will add, in my .log file I found this line:
`2022-11-26 18:35:46.584 ERROR_ONCE DX11BACKEND (16092): texture 'a29b_01_flir' not found. Asked from ' '
`

**Comment by Major-dinner** [comment]
I have the same issue. I can run all previous versions in 2.8 except the latest release

**Comment by luciusMessias** [comment]
Same issue with me. I try to create a simple mission with just one A29B controled by "veteran" and works normally. but if i try configure to "client" or "player" crash to desktop!!!

**Comment by luciusMessias** [comment]
> 

how can I download any presvious release?

**Comment by luciusMessias** [comment]
https://forum.dcs.world/topic/265017-a-29-super-tucano/page/29/

solution by URBI

**Comment by Major-dinner** [comment]
solution by URBI....absolutely awesome. I downloaded it just pasted the a29 folder in my aircraft folder and tried the mission editor. Works great. First time i have actually had all the cockpit textures, Thanks so much URBI

**Comment by Major-dinner** [comment]
Fantastic. I downloaded the latest update and everything working including the flir

**Comment by luizrenault** [comment]
Just download latest release.

**Comment by Major-dinner** [comment]
Just want to be clear. I finally figured out I had to click on the green code button and download that file. I had previously been just downloading the one that said latest release...that one didn't work.
