### ISSUE TITLE
DCS Crash when selecting A-29 

### ISSUE THREAD

**Issue by guiteles15** [luizrenault/a-29b-community#114]
Hello, my DCS is crashing every time I try to start any mission with the A-29B, and the following message appears: 

"Unfortunately DCS crashed. Allow DCS to gather additional debug info using dxdiag.exe?" and "Log file has been packed to be sent to support service. You can open its path in explorer for quick acess."

And when I open the cited path, these logs appear:

[failed.txt](https://github.com/luizrenault/a-29b-community/files/10230424/failed.txt)

What's the problem? please, I can't play!

**Comment by guiteles15** [comment]
version 0.3.1b

**Comment by luciusMessias** [comment]
https://forum.dcs.world/topic/265017-a-29-super-tucano/page/29/

solution by URBI

**Comment by luizrenault** [comment]
Just download latest release.
