### ISSUE TITLE
crashing again after this weeks DCS update

### ISSUE THREAD

**Issue by Major-dinner** [luizrenault/a-29b-community#115]
After finally being able to fly this great mod again DCS updated yesterday and I can no longer load this mod without a crash to the desktop.  Why is this mod so sensitive. A4e and Blackhawk all still load.  I have to admit this is my favorite plane to fly in DCS and I hope its updated again soon.

**Comment by luizrenault** [comment]
Try the latest release dll.

**Comment by Major-dinner** [comment]
Fantastic. All working again. Thanks so much. Your mod is absolutely amazing.On 12 Mar 2023 23:51, luizrenault ***@***.***> wrote:
Try the latest release dll.
