### ISSUE TITLE
MOD não aparece no editor de missões como aeronave selecionável

### ISSUE THREAD

**Issue by Ovelha1926** [luizrenault/a-29b-community#130]
Boa tarde pessoal, tudo bem? 
Sou novo no jogo e instalei recentemente o Super Tucano na pasta Usuarios/SavedGames/DCS/Mods/Aircrafts

Ela está funcionando perfeitamente no instant action e no training, contudo, não aparece como aeronave selecionável no editor de missões. Alguém sabe como resolver isso? 

ATt.

**Comment by Zibelli** [comment]
Você tem que selecionar um país que tenha a aeronave disponivel para ela aparecer no editor de missões. Adiciona uma aeronave no mapa e define o país dela como Brasil, a-29b deve aparecer na lista de seleção.
