### ISSUE TITLE
Cold start switches positions

### ISSUE THREAD

**Issue by jean-knapp** [luizrenault/a-29b-community#15]
The following switches config should be expected at cold start:

-Avionics Master - OFF
-ECS - MAN
-Emer Speed Brake - NORMAL
-Flaps - DN
-DVR - OFF
-EGI - OFF
-UFCP - Max BRT

**Comment by luizrenault** [comment]
Other sources said that the first and last not necessarily, but the for the others the information proceed. Will be implemented.

**Comment by jean-knapp** [comment]
First is optional, depending on the squadron. Some maintenance turn it off, some doesn't, I never read their manual, but I honestly never saw the UFCP turned off. It has always been on for me.

**Comment by luizrenault** [comment]
Hum. Maybe it can be an option on special menu, when i figure out how to do this..

Thank a lot for the contribution.

Looked you up. Very welcome to contribute to code development.

**Comment by luizrenault** [comment]
-Avionics Master - OFF - **Changed**
-ECS - MAN - **Changed**
-Emer Speed Brake - NORMAL-  **Changed**
-Flaps - DN -  **Changed**
-DVR - OFF -  **Changed**
-EGI - OFF -  **Changed**
-UFCP - Max BRT - **Changed**
