### ISSUE TITLE
Master Warning and Master Caution stay on even after pressed.

### ISSUE THREAD

**Issue by jean-knapp** [luizrenault/a-29b-community#18]
The Master Warning and Master Caution lights should turn off after they are pressed, although they currently kinda stay on (comparing their default blinking brightness, and comparing with the Fire and Brake On lights).

**Comment by luizrenault** [comment]
Hi. Thanks for the feedback. Do you have a source for that?
Is to my knowledge that it should stop blinking and stay on after acknowledged (pressed) until the condition goes off.

**Comment by luizrenault** [comment]
The brightness is very low, mainly in clear day conditions, though.

**Comment by luizrenault** [comment]
Fixed.
