### ISSUE TITLE
Static blades, Clean Config No Pylons No Guns, retractable step, Airbrake???

### ISSUE THREAD

**Issue by MaximusRZ** [luizrenault/a-29b-community#24]
The animation of the propeller when you pause the game will show it static showing the 5 blades, also in AI controlled airplanes the propeller remains fixed all the time...

Paused...
![image](https://user-images.githubusercontent.com/80410123/111345272-df36f980-865b-11eb-937c-f23396362a04.png)

Playing...
![image](https://user-images.githubusercontent.com/80410123/111345382-fd9cf500-865b-11eb-9875-6f78018b85cf.png)

Also is missing the "retractable Step (12)", it is the step that goes down with the landing gear to help to go up and down the plane, it is located under the left FLAP.
![image](https://user-images.githubusercontent.com/80410123/111346269-d135a880-865c-11eb-9e64-82c8f8a6d48e.png)

Also The Airbrake!! The animation is missing but the imput is there. 

also it would be very useful to be able to remove the armament pylons and cannons to use the plane in clean configuration for aerobatics. 
like this...

![image](https://user-images.githubusercontent.com/80410123/111345180-ca5a6600-865b-11eb-9679-5d44f186d5cd.png)

I really like this plane!! Thanks

**Comment by jean-knapp** [comment]
> The animation of the propeller when you pause the game will show it static showing the 5 blades, also in AI controlled airplanes the propeller remains fixed all the time...
> 
> Paused...
> ![image](https://user-images.githubusercontent.com/80410123/111345272-df36f980-865b-11eb-937c-f23396362a04.png)
> 
> Playing...
> ![image](https://user-images.githubusercontent.com/80410123/111345382-fd9cf500-865b-11eb-9875-6f78018b85cf.png)
> 
> Also is missing the "retractable Step (12)", it is the step that goes down with the landing gear to help to go up and down the plane, it is located under the left FLAP.
> ![image](https://user-images.githubusercontent.com/80410123/111346269-d135a880-865c-11eb-9e64-82c8f8a6d48e.png)
> 
> Also The Airbrake!! The animation is missing but the imput is there.
> 
> also it would be very useful to be able to remove the armament pylons and cannons to use the plane in clean configuration for aerobatics.
> like this...
> 
> ![image](https://user-images.githubusercontent.com/80410123/111345180-ca5a6600-865b-11eb-9679-5d44f186d5cd.png)
> 
> I really like this plane!! Thanks

The A-29 doesn't get that better for acrobatics without pylons or machine-guns. It's much heavier and sturdier than the Tucano.

**Comment by luizrenault** [comment]
Blades fixed. Removable pylons implemented. Retractable step will be implemented.
