### ISSUE TITLE
NVG switch bug?

### ISSUE THREAD

**Issue by mreisr** [luizrenault/a-29b-community#39]
I don't know if this is a bug or a real pattern of the real aircraft but when the NVG switch is kept in the NORM position the cockpit has a greenish tinge

![1](https://user-images.githubusercontent.com/81477386/112724901-3c506c00-8ef4-11eb-9bb7-203edb492e54.jpg)

![2](https://user-images.githubusercontent.com/81477386/112724905-3eb2c600-8ef4-11eb-81d4-773c3c98f6bd.jpg)

**Comment by luizrenault** [comment]
Fixed with new textures.
