### ISSUE TITLE
AI not able to takeoff from runways

### ISSUE THREAD

**Issue by Ru55ellPalin** [luizrenault/a-29b-community#40]
I've found that AI aircraft seem to be unable to takeoff from runways and instead will crash at the end of them. 

Nice mod btw I'm loving it :)

**Comment by Ru55ellPalin** [comment]
The AI aircraft don't seem to be able to accelerate to gain enough speed for flight. I used Kobuleti for one to take off from and at the end of the runway, it was only at 135kts before it exploded on the ground.

**Comment by rudel-chw** [comment]
Yes, it happens to me too. Here is a track file.
[A-29B - AI doesnt take off.zip](https://github.com/luizrenault/a-29b-community/files/6243358/A-29B.-.AI.doesnt.take.off.zip)

**Comment by luizrenault** [comment]
Fixed. There were some detail on the SFM. AI now can take off with maximum weight.
