### ISSUE TITLE
Hud position - default position of ejection seat

### ISSUE THREAD

**Issue by unknownpilot** [luizrenault/a-29b-community#54]
I suggest to move the seat up to a position where the HUD is set as the video below:
https://www.youtube.com/watch?v=TLxF_l4-bK0
I mean, the pilot sees all the informations at the screen without any space above them.
Other possibility is to create a bind where we can move the seat by ourselves.

**Comment by allanhofmann** [comment]
I agree with unknownpilot. The first thing I do when the mission starts  is to "raise the seat".

**Comment by luizrenault** [comment]
Fixed.
