### ISSUE TITLE
AG Gun CCIP windage

### ISSUE THREAD

**Issue by allanhofmann** [luizrenault/a-29b-community#60]
I was running some Gun and Rocket attack on ground units and noticed a consistent error on the CCIP when there is ground level winds. 

On the attached image you can see how the CCIP is indicating a point vertical to the Velocity Indicator, but the bullets are falling on a line vertical to the "gun cross" (or "airplane datum"). 

The same behavior occurs with rockets. When I remove the wind in the mission editor, the CCIP works just fine.

 I don't know if this is actual behavior, but I suspect the bullets and rockets would not be so influenced by the wind as the airplane does, so the CCIP should not indicate such a windage correction.

![Digital Combat Simulator  Black Shark Screenshot 2021 04 24 - 21 17 45 36](https://user-images.githubusercontent.com/81055015/115976600-eba94e80-a545-11eb-99b9-475bc7163775.png)

**Comment by luizrenault** [comment]
Fixed.
