### ISSUE TITLE
Communication Menu Doesnt Work

### ISSUE THREAD

**Issue by HACKER-A29Pilot** [luizrenault/a-29b-community#71]
I Tried to use the communication menu with IA AWACS and didnt work, the commucation menu is displayed but didnt allow any interaction with the IA AWACS freq. or IA ATC, i tried with easy comunication "ON" and "OFF", I tried to adjust the AM Freq, but I see that the COM 1 and COM 2, doesnt supprot this range of Freqs. is it posible to FIX this issue to allow the intercept simulation Mission whit IA AWACS interaction or AFAC - JTAC integration for simulate CAS and CSAR misions.

if Anyone knows the solutions or any alternative to fligth the A-29B with IA AWACS, I will hear you

**Comment by luizrenault** [comment]
You have to bind radio ptts.
