### ISSUE TITLE
CCIP Parameters correction

### ISSUE THREAD

**Issue by HACKER-A29Pilot** [luizrenault/a-29b-community#72]
from my experience, the Dive CCIP Parameters for bomb need a readjust, In Colombian Air Force we do CCIP since 15° at low level attacks (called CCIP pop up) until 35°dive, for CCIP Attacks at altitude blocks between 4000 AGL until 14.000 for MK 82, i tried do some attack on DCS with 6000 AGL or CCIP low level attacks and was impossible, the HUD didnt show correct symbology, 40°-45° degrees is too excesive, is easier exceed the limitations and requires very high altitude, in a mid or low altitude these parameters dont works

**Comment by luizrenault** [comment]
Corrected.
