### ISSUE TITLE
Add CCIP Delayed posibility

### ISSUE THREAD

**Issue by HACKER-A29Pilot** [luizrenault/a-29b-community#74]
Add the CCIP Delayed is the solution for CCIP Problems and allow a low altitude and low dive angle deliveries.
![16230833228157119331877953512020](https://user-images.githubusercontent.com/81787850/121056165-8de26600-c783-11eb-8d9b-218af1a4f7b5.jpg)
![16230833625564467574824116381610](https://user-images.githubusercontent.com/81787850/121056275-a6eb1700-c783-11eb-86db-a2b824d98486.jpg)

**Comment by HACKER-A29Pilot** [comment]
![8CC56260-F513-4C9D-95BD-A88D2B331157](https://user-images.githubusercontent.com/81787850/137951394-9c7d0344-3bb0-4fb4-bad8-bb3e6b930dea.png)
![BBBBA45D-428A-4A95-A9FC-25033855E6B2](https://user-images.githubusercontent.com/81787850/137951403-dbfadc15-84ea-4b50-a2aa-eaa515560ce8.png)
![55F549FD-6555-4C53-9B4A-43157109855D](https://user-images.githubusercontent.com/81787850/137951409-d4f3761b-8e42-46c0-9894-60bb36a35492.png)
![364428AB-FBDB-4A37-B1B3-D4D643EA327D](https://user-images.githubusercontent.com/81787850/137951413-998368a6-bd5e-473d-8228-c9884bacc85e.png)
M

**Comment by luizrenault** [comment]
Implemented.
