### ISSUE TITLE
A-29 Armaments

### ISSUE THREAD

**Issue by denissoliveira** [luizrenault/a-29b-community#77]
![image](https://user-images.githubusercontent.com/7603843/122254008-160eec80-cea3-11eb-836c-2f236d8f89d1.png)
![image](https://user-images.githubusercontent.com/7603843/122254048-21faae80-cea3-11eb-8352-91159818e521.png)
![image](https://user-images.githubusercontent.com/7603843/122254078-2757f900-cea3-11eb-8ad8-700c40c9eac3.png)

**Comment by KingAntonio** [comment]
https://defense.embraer.com/global/en/super-tucano
They have a 3d picture (not a model)of the external pods here if that helps

**Comment by luizrenault** [comment]
Added 7x70mm rocket
Will add MK-81 and MK82 LGB

**Comment by luizrenault** [comment]
MK82 LGB added.

**Comment by luizrenault** [comment]
MK-81 Added.
