### ISSUE TITLE
Default position of the SEAT

### ISSUE THREAD

**Issue by HACKER-A29Pilot** [luizrenault/a-29b-community#83]
Good afternoon

CCIP Delayed Works Fine with the last devel !!! Thanks.

Is possible to correct the default position of the camera (seat) ?    We have to set it up a few upper than the default to be able to see all HUD Simbology during a CCIP delivery.

I guess, if you set up the HEADING BOX on the upper limit of the HUD by default, It will work fine.  

I'll send you a picture about that
As you can see in the picture the HDG BOX is setted up on the upper limit of the HUD, it worked fine for us.

![Uploading 20211024_124434.jpg…]()

**Comment by luizrenault** [comment]
Solved. Moved it up a little.
