### ISSUE TITLE
Can't create new waypoints via UFPC

### ISSUE THREAD

**Issue by dybal** [luizrenault/a-29b-community#93]
When choosing wpt (key 4) in the UFPC and cycling through the existing waypoints (0 to n), the cycle goes from the last defined waypoint (n) to the first airport (90), without showing waypoint n+1 with zeroed data to be filled in (if the player so chooses) and saved as a new waypoint at the route end.

Version 0.3.0b

**Comment by jean-knapp** [comment]
Switch from FYT mode to WP mode.

**Comment by dybal** [comment]
Thanks! It didn't occur me there were two modes to that page.
